#!/usr/bin/env python3
"""
Convert 3D coordinate files to PDB format.

Reads x, y, z coordinates (one bead per line) and writes a standard PDB
file with CA atoms in GLY residues on chain A.  Coordinates are normalized
to the +/-50 range to match pMMC's PdbWriter convention.

Supported input formats:
  - Whitespace-delimited text (3 columns: x y z)
  - NumPy .npy files (Nx3 array)
  - miniMDS output format
  - ChromSDE output format

Usage:
    python coords_to_pdb.py -i coords.txt -o model.pdb [--no-normalize]
    python coords_to_pdb.py -i coords.npy -o model.pdb
    python coords_to_pdb.py -i coords.txt -o model.pdb --chr chr6
                            --start 25000000 --res 5000

The optional --chr, --start, and --res flags add REMARK 999 records with
genomic metadata, matching pMMC's PDB output style.
"""

import argparse
import sys
import os


def read_coordinates(path):
    """Read Nx3 coordinates from text or .npy file."""
    if path.endswith(".npy"):
        import numpy as np
        coords = np.load(path)
        if coords.ndim != 2 or coords.shape[1] != 3:
            raise ValueError(f"Expected Nx3 array, got shape {coords.shape}")
        return coords.tolist()

    coords = []
    with open(path, "r") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("//"):
                continue
            parts = line.split()
            # Accept lines with at least 3 numeric columns (skip header rows)
            try:
                x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
            except (ValueError, IndexError):
                # Try columns 1-3 (some formats have an index in column 0)
                try:
                    x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                except (ValueError, IndexError):
                    continue
            coords.append((x, y, z))

    if not coords:
        raise ValueError(f"No coordinates found in {path}")
    return coords


def normalize_coords(coords, target_range=50.0):
    """Normalize coordinates to +/-target_range, centered at origin."""
    xs = [c[0] for c in coords]
    ys = [c[1] for c in coords]
    zs = [c[2] for c in coords]

    cx = (max(xs) + min(xs)) / 2.0
    cy = (max(ys) + min(ys)) / 2.0
    cz = (max(zs) + min(zs)) / 2.0

    span = max(max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs))
    if span < 1e-10:
        return [(0.0, 0.0, 0.0)] * len(coords)

    scale = (2.0 * target_range) / span
    return [((x - cx) * scale, (y - cy) * scale, (z - cz) * scale)
            for x, y, z in coords]


def write_pdb(coords, output_path, chrom="chr6", start_bp=0, resolution=5000,
              label="model"):
    """Write PDB file with CA atoms in GLY residues, chain A."""
    n = len(coords)

    with open(output_path, "w") as f:
        f.write(f"REMARK   1 Generated by coords_to_pdb.py (pMMC toolkit)\n")
        f.write(f"REMARK   2 {n} beads, {label}\n")
        if chrom and start_bp >= 0:
            end_bp = start_bp + n * resolution
            f.write(f"REMARK   3 Region: {chrom}:{start_bp}-{end_bp} "
                    f"({resolution} bp/bead)\n")

        # REMARK 999: genomic metadata per residue (matching pMMC convention)
        if chrom and start_bp >= 0:
            f.write("REMARK 999\n")
            f.write("REMARK 999 GENOMIC COORDINATES\n")
            f.write("REMARK 999  RESID  CHROMOSOME  START       END\n")
            for i in range(n):
                bp_start = start_bp + i * resolution
                bp_end = bp_start + resolution
                f.write(f"REMARK 999  {i+1:5d}  {chrom:<12s}"
                        f"{bp_start:>11d}{bp_end:>11d}\n")

        # HELIX record spanning entire chain
        f.write(f"HELIX    1   A GLY A    1  GLY A {min(n, 9999):4d}  1"
                f"{'':>30s}{n:5d}\n")

        # ATOM records
        for i, (x, y, z) in enumerate(coords):
            atom_num = (i + 1) % 100000  # PDB limit: 99999
            res_num = (i + 1) % 10000    # PDB limit: 9999
            f.write(
                f"ATOM  {atom_num:5d}  CA  GLY A{res_num:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}"
                f"  1.00  0.00           C\n"
            )

        # CONECT records for backbone connectivity
        for i in range(n - 1):
            a1 = (i + 1) % 100000
            a2 = (i + 2) % 100000
            f.write(f"CONECT{a1:5d}{a2:5d}\n")

        f.write("END\n")


def main():
    parser = argparse.ArgumentParser(
        description="Convert 3D coordinate files to PDB format")
    parser.add_argument("-i", "--input", required=True,
                        help="Input coordinate file (.txt or .npy)")
    parser.add_argument("-o", "--output", required=True,
                        help="Output PDB file path")
    parser.add_argument("--no-normalize", action="store_true",
                        help="Skip coordinate normalization to +/-50 range")
    parser.add_argument("--chr", default="chr6",
                        help="Chromosome name (default: chr6)")
    parser.add_argument("--start", type=int, default=25000000,
                        help="Start position in bp (default: 25000000)")
    parser.add_argument("--res", type=int, default=5000,
                        help="Resolution in bp per bead (default: 5000)")
    parser.add_argument("--label", default="external_tool",
                        help="Label for REMARK header")
    args = parser.parse_args()

    coords = read_coordinates(args.input)
    print(f"Read {len(coords)} beads from {args.input}")

    if not args.no_normalize:
        coords = normalize_coords(coords, target_range=50.0)
        print("Normalized to +/-50 range")

    write_pdb(coords, args.output, chrom=args.chr, start_bp=args.start,
              resolution=args.res, label=args.label)
    print(f"PDB written to {args.output}")


if __name__ == "__main__":
    main()
