/**
 * @file Static.hpp
 * @brief Storage definitions for static class members.
 *
 * This file provides the single definition point for all static member
 * variables that cannot use C++17 inline variables (due to nvcc limitations).
 * Include this file from exactly one translation unit (main.cpp).
 */

#ifndef STATIC_HPP_
#define STATIC_HPP_

#include <Settings.hpp>

// Settings static member definitions
bool Settings::initialized;
bool Settings::use2D;
int Settings::debug;
bool Settings::randomWalk;
bool Settings::useInputCache;
size_t Settings::maxMemoryMB;
int Settings::outputLevel;
int Settings::loopDensity;
std::string Settings::chromosomes;
std::string Settings::outputDir;
std::string Settings::label;
int Settings::seed;
int Settings::ensembleSize;
std::string Settings::outputFormat;
std::string Settings::annotationDir;
int Settings::maxLevel;
int Settings::lengthLimit;
int Settings::chrNumberLimit;
bool Settings::useNewFileFormat;
std::string Settings::selectedFactors;
std::string Settings::cellLineList;
std::string Settings::action;
std::string Settings::inputFile2;
std::string Settings::bedRegionsFile;
std::string Settings::pattern;
int Settings::level;
int Settings::resolution;
bool Settings::addHeader;
int Settings::extractStart;
int Settings::extractEnd;
std::string Settings::bedFilePath;
std::string Settings::bedpeFilePath;
int Settings::numLoops;
int Settings::milestoneFailsThreshold;
int Settings::cudaBlocksMultiplier;
int Settings::cudaThreadsPerBlock;
std::string Settings::dataDirectory;
std::string Settings::dataAnchors;
std::string Settings::dataPetClusters;
std::string Settings::dataSingletons;
std::string Settings::dataSingletonsInter;
std::string Settings::dataFactors;
bool Settings::dataSplitSingletonFilesByChr;
std::string Settings::dataCentromeres;
std::string Settings::dataSegmentsSplit;
std::string Settings::dataSegmentHeatmap;
std::string Settings::templateSegment;
float Settings::templateScale;
bool Settings::useDensity;
std::string Settings::densityMapFile;
float Settings::densityScale;
float Settings::densityInfluence;
float Settings::densityWeight;
bool Settings::useTelomerePositions;
vector3 Settings::telomere_1_position;
vector3 Settings::telomere_2_position;
float Settings::ibRandomWalkJumps;
std::string Settings::distHeatmap;
float Settings::distHeatmapScale;
bool Settings::rewiringEnabled;
int Settings::rewiringCertaintyThreshold;
bool Settings::useCTCFMotifOrientation;
bool Settings::motifsSymmetric;
float Settings::motifOrientationWeigth;
bool Settings::useAnchorHeatmap;
float Settings::anchorHeatmapInfluence;
float Settings::anchorHeatmapDistWeight;
bool Settings::useSubanchorHeatmap;
bool Settings::useGlobalAnchorRefinement;
float Settings::noiseAnchorSmall;
int Settings::stressRefineIterations;
float Settings::stressRefineLR;
float Settings::subanchorHeatmapInfluence;
float Settings::subanchorHeatmapDistWeight;
int Settings::subanchorEstimateDistancesReplicates;
int Settings::subanchorEstimateDistancesSteps;
float Settings::subanchorLoopLoopInteractionsScale;
int Settings::maxPETClusterLength;
float Settings::longPETClustersEffectPower;
float Settings::longPETClustersEffectScale;
int Settings::segmentSize;
int Settings::simulationStepsLevelChr;
int Settings::simulationStepsLevelSegment;
int Settings::simulationStepsLevelAnchor;
int Settings::simulationStepsLevelSubanchor;
float Settings::noiseCoefficientLevelChr;
float Settings::noiseCoefficientLevelSegment;
float Settings::noiseCoefficientLevelAnchor;
float Settings::noiseCoefficientLevelSubanchor;
float Settings::heatmapInterScaling;
float Settings::heatmapDistanceHeatmapStretching;
float Settings::freqToDistHeatmapScale;
float Settings::freqToDistHeatmapPower;
float Settings::freqToDistHeatmapScaleInter;
float Settings::freqToDistHeatmapPowerInter;
float Settings::countToDistA;
float Settings::countToDistScale;
float Settings::countToDistShift;
float Settings::countToDistBaseLevel;
float Settings::genomicLengthToDistPower;
float Settings::genomicLengthToDistScale;
float Settings::genomicLengthToDistBase;
float Settings::springConstantStretch;
float Settings::springConstantSqueeze;
float Settings::springAngularConstant;
float Settings::springConstantStretchArcs;
float Settings::springConstantSqueezeArcs;
float Settings::loopStiffness;
float Settings::loopEquilibriumDistance;
std::string Settings::loopConstraintsFile;
std::string Settings::mergedInputFile;
std::string Settings::inputFormat;
std::string Settings::inputFile;
int Settings::contactResolution;
float Settings::maxTempHeatmap;
float Settings::dtTempHeatmap;
float Settings::tempJumpScaleHeatmap;
float Settings::tempJumpCoefHeatmap;
float Settings::MCstopConditionImprovementHeatmap;
int Settings::MCstopConditionMinSuccessesHeatmap;
int Settings::MCstopConditionStepsHeatmap;
float Settings::maxTempHeatmapDensity;
float Settings::dtTempHeatmapDensity;
float Settings::tempJumpScaleHeatmapDensity;
float Settings::tempJumpCoefHeatmapDensity;
float Settings::MCstopConditionImprovementHeatmapDensity;
int Settings::MCstopConditionMinSuccessesHeatmapDensity;
int Settings::MCstopConditionStepsHeatmapDensity;
float Settings::maxTemp;
float Settings::dtTemp;
float Settings::tempJumpScale;
float Settings::tempJumpCoef;
float Settings::MCstopConditionImprovement;
int Settings::MCstopConditionMinSuccesses;
int Settings::MCstopConditionSteps;
float Settings::weightDistSmooth;
float Settings::weightAngleSmooth;
float Settings::maxTempSmooth;
float Settings::dtTempSmooth;
float Settings::tempJumpScaleSmooth;
float Settings::tempJumpCoefSmooth;
float Settings::MCstopConditionImprovementSmooth;
int Settings::MCstopConditionMinSuccessesSmooth;
int Settings::MCstopConditionStepsSmooth;
bool Settings::energyTraceEnabled;
int Settings::energyTraceInterval;
std::string Settings::initMethod;
unsigned int Settings::gpuSeed;
float Settings::sphere_radius;
std::string Settings::enhancerAnnotationFile;
std::string Settings::promoterAnnotationFile;
std::string Settings::epigeneticAnnotationFile;

#endif /* STATIC_HPP_ */
